### PR TITLE
Fix an infinite loop when parsing an INFO tag.

### LINKED ISSUE #472: Infinite loop with fuzzed file (wave)
Parsing the following file with the tagreader example results in an infinite loop.
https://www.dropbox.com/s/vljhvl7wbx4vwh5/taglib_wave_infloop.wav

<pre>
$ gdb --args ~/repository/taglib/build/examples/tagreader taglib_wave_infloop.wav
GNU gdb (Gentoo 7.7.1 p1) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/cocobo/repository/taglib/build/examples/tagreader...done.
(gdb) r
TagLib: String::UTF8toUTF16() - Unicode conversion error.
TagLib: String::UTF8toUTF16() - Unicode conversion error.
...
TagLib: String::UTF8toUTF16() - Unicode conversion error.
TagLib: String::UTF8toUTF16() - Unicode conversion error.
^C
Program received signal SIGINT, Interrupt.
0x00007ffff6e03550 in __write_nocancel () from /lib64/libc.so.6
(gdb) bt full
#0  0x00007ffff6e03550 in __write_nocancel () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007ffff6d9e563 in _IO_file_write () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007ffff6d9dc23 in new_do_write () from /lib64/libc.so.6
No symbol table info available.
#3  0x00007ffff6d9eb76 in _IO_file_xsputn () from /lib64/libc.so.6
No symbol table info available.
#4  0x00007ffff6d9444d in fwrite () from /lib64/libc.so.6
No symbol table info available.
#5  0x00007ffff76774f5 in std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long) ()
   from /usr/lib/gcc/x86_64-pc-linux-gnu/4.8.3/libstdc++.so.6
No symbol table info available.
#6  0x00007ffff7a7f8dd in operator<< <char, std::char_traits<char>, std::allocator<char> > (
    __str="TagLib: String::UTF8toUTF16() - Unicode conversion error.\n", __os=...)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.8.3/include/g++-v4/bits/basic_string.h:2758
No locals.
#7  operator<< (s=..., str=...) at /home/cocobo/repository/taglib/taglib/toolkit/tstring.cpp:862
No locals.
#8  0x00007ffff7aa13ca in TagLib::debug (s=...)
    at /home/cocobo/repository/taglib/taglib/toolkit/tdebug.cpp:48
No locals.
#9  0x00007ffff7a785ae in UTF8toUTF16 (dstLength=94, dst=<optimized out>, srcLength=94, 
    src=0x6127d6 "Q Sound") at /home/cocobo/repository/taglib/taglib/toolkit/tstring.cpp:113
        len = 0
        dstBegin = 0x613198 L""
        dstEnd = <optimized out>
        srcBegin = 0x6127e6 <incomplete sequence \373>
        srcEnd = 0x612834 ""
        result = <optimized out>
#10 TagLib::String::copyFromUTF8 (this=0x7fffffffd600, s=0x6127d6 "Q Sound", length=94)
    at /home/cocobo/repository/taglib/taglib/toolkit/tstring.cpp:754
        length = 94
        s = 0x6127d6 "Q Sound"
        this = 0x7fffffffd600
#11 0x00007ffff7a7dfe6 in TagLib::String::String (this=0x7fffffffd600, v=..., t=<optimized out>)
    at /home/cocobo/repository/taglib/taglib/toolkit/tstring.cpp:254
No locals.
#12 0x00007ffff7adab8d in TagLib::RIFF::Info::StringHandler::parse (this=<optimized out>, data=...)
    at /home/cocobo/repository/taglib/taglib/riff/wav/infotag.cpp:74
No locals.
#13 0x00007ffff7ae12cc in TagLib::RIFF::Info::Tag::parse (this=this@entry=0x612b90, data=...)
    at /home/cocobo/repository/taglib/taglib/riff/wav/infotag.cpp:261
        <b>size = 4294967279</b>
        <b>p = 14</b>
#14 0x00007ffff7ae224a in TagLib::RIFF::Info::Tag::Tag (this=0x612b90, data=...)
    at /home/cocobo/repository/taglib/taglib/riff/wav/infotag.cpp:93
No locals.
#15 0x00007ffff7ad8880 in TagLib::RIFF::WAV::File::read (this=this@entry=0x611cd0, 
    readProperties=readProperties@entry=true, 
    propertiesStyle=propertiesStyle@entry=TagLib::AudioProperties::Average)
    at /home/cocobo/repository/taglib/taglib/riff/wav/wavfile.cpp:203
        data = {_vptr.ByteVector = 0x7ffff7dd4650 <vtable for TagLib::ByteVector+16>, static null = {
            _vptr.ByteVector = 0x7ffff7dd4650 <vtable for TagLib::ByteVector+16>, 
            static null = <same as static member of an already seen type>, d = 0x610b40}, 
          d = 0x6125c0}
        type = {_vptr.ByteVector = 0x7ffff7dd4650 <vtable for TagLib::ByteVector+16>, static null = {
            _vptr.ByteVector = 0x7ffff7dd4650 <vtable for TagLib::ByteVector+16>, 
            static null = <same as static member of an already seen type>, d = 0x610b40}, 
          d = 0x612ac0}
        name = {_vptr.String = 0x7ffff7dd4510 <vtable for TagLib::String+16>, static null = {
            _vptr.String = 0x7ffff7dd4510 <vtable for TagLib::String+16>, 
            static null = <same as static member of an already seen type>, 
            static WCharByteOrder = TagLib::String::UTF16LE, d = 0x610af0}, 
          static WCharByteOrder = TagLib::String::UTF16LE, d = 0x612870}
        i = 2
        formatData = {_vptr.ByteVector = 0x7ffff7dd4650 <vtable for TagLib::ByteVector+16>, 
          static null = {_vptr.ByteVector = 0x7ffff7dd4650 <vtable for TagLib::ByteVector+16>, 
            static null = <same as static member of an already seen type>, d = 0x610b40}, 
          d = 0x6126c0}
#16 0x00007ffff7ad92bf in TagLib::RIFF::WAV::File::File (this=0x611cd0, file=<optimized out>, 
    readProperties=<optimized out>, propertiesStyle=TagLib::AudioProperties::Average)
    at /home/cocobo/repository/taglib/taglib/riff/wav/wavfile.cpp:78
No locals.
#17 0x00007ffff7b9988b in TagLib::FileRef::create (fileName=0x7fffffffdea2 "taglib_wave_infloop.wav", 
    readAudioProperties=<optimized out>, audioPropertiesStyle=TagLib::AudioProperties::Average)
    at /home/cocobo/repository/taglib/taglib/fileref.cpp:271
        it = <optimized out>
        ext = {_vptr.String = 0x7ffff7dd4510 <vtable for TagLib::String+16>, static null = {
            _vptr.String = 0x7ffff7dd4510 <vtable for TagLib::String+16>, 
            static null = <same as static member of an already seen type>, 
            static WCharByteOrder = TagLib::String::UTF16LE, d = 0x610af0}, 
          static WCharByteOrder = TagLib::String::UTF16LE, d = 0x611d70}
#18 0x00007ffff7b99f72 in TagLib::FileRef::FileRef (this=0x7fffffffd8f0, fileName=<optimized out>, 
    readAudioProperties=<optimized out>, audioPropertiesStyle=<optimized out>)
    at /home/cocobo/repository/taglib/taglib/fileref.cpp:83
No locals.
#19 0x0000000000401d80 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/cocobo/repository/taglib/examples/tagreader.cpp:41
        f = {_vptr.FileRef = 0x7ffff7dd6690 <vtable for TagLib::FileRef+16>, d = 0x7ffff6d31b60}
        i = <optimized out>
#20 0x00007ffff6d4adc5 in __libc_start_main () from /lib64/libc.so.6
No symbol table info available.
#21 0x0000000000405341 in _start ()
No symbol table info available.
(gdb) up 13
#13 0x00007ffff7ae12cc in TagLib::RIFF::Info::Tag::parse (this=this@entry=0x612b90, data=...)
    at /home/cocobo/repository/taglib/taglib/riff/wav/infotag.cpp:261
261         d->fieldListMap[data.mid(p, 4)] = TagPrivate::stringHandler->parse(data.mid(p + 8, size));
(gdb) list
256     void RIFF::Info::Tag::parse(const ByteVector &data)
257     {
258       uint p = 4;
259       while(p < data.size()) {
260         const uint size = data.toUInt(p + 4, false);
261         d->fieldListMap[data.mid(p, 4)] = TagPrivate::stringHandler->parse(data.mid(p + 8, size));
262
263         <b>p += ((size + 1) & ~1) + 8;</b>
264       }
265     }
(gdb) break infotag.cpp:262
Breakpoint 1 at 0x7ffff7ae1a7b: file /home/cocobo/repository/taglib/taglib/riff/wav/infotag.cpp, line 262.
(gdb) c
Continuing.
TagLib: String::UTF8toUTF16() - Unicode conversion error.

Breakpoint 1, TagLib::RIFF::Info::Tag::parse (this=this@entry=0x612b90, data=...)
    at /home/cocobo/repository/taglib/taglib/riff/wav/infotag.cpp:263
263         p += ((size + 1) & ~1) + 8;
(gdb) info local
<b>size = 4294967279</b>
<b>p = 14</b>
(gdb) c
Continuing.

Breakpoint 1, TagLib::RIFF::Info::Tag::parse (this=this@entry=0x612b90, data=...)
    at /home/cocobo/repository/taglib/taglib/riff/wav/infotag.cpp:263
263         p += ((size + 1) & ~1) + 8;
(gdb) info local
<b>size = 0</b>
<b>p = 6</b>
(gdb) c
Continuing.
TagLib: String::UTF8toUTF16() - Unicode conversion error.

Breakpoint 1, TagLib::RIFF::Info::Tag::parse (this=this@entry=0x612b90, data=...)
    at /home/cocobo/repository/taglib/taglib/riff/wav/infotag.cpp:263
263         p += ((size + 1) & ~1) + 8;
(gdb) info local
<b>size = 4294967279</b>
<b>p = 14</b>
(gdb) c
Continuing.

Breakpoint 1, TagLib::RIFF::Info::Tag::parse (this=this@entry=0x612b90, data=...)
    at /home/cocobo/repository/taglib/taglib/riff/wav/infotag.cpp:263
263         p += ((size + 1) & ~1) + 8;
(gdb) info local
<b>size = 0</b>
<b>p = 6</b>
(gdb) print p + ((size + 1) & ~1) + 8
$1 = 14
</pre>

### PR DESCRIPTION
**Pull request by TsudaKageyu**
Fixes #472.

### CODE REVIEW

File: tests/test_wav.cpp [hunk 1]
```diff
@@ -67,7 +68,16 @@ class TestWAV : public CppUnit::TestFixture
     CPPUNIT_ASSERT(!f->hasID3v2Tag());
     CPPUNIT_ASSERT(f->hasInfoTag());
     delete f;
- }
+  }
+
+  void testFuzzedFiles()
```
Comment (lalinsky) [inline tests/test_wav.cpp]: Can you please split this to one test per file?

**Comment by TsudaKageyu** [comment]
Ok. I did it.

**Comment by lalinsky** [comment]
Thank you.
